kind: pipeline
type: docker
name: pyaussiebb

steps:
- name: testbuild
  image: python:3.8
  commands:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install -q pytest requests pylint loguru aiohttp
  - python3 -m pip install -r test-requirements.txt
  - pylint aussiebb
  - pylint aussiebb.asyncio
  - pytest
  environment:
    username:
      from_secret: username
    password:
      from_secret: password
    username2:
      from_secret: username2
    password2:
      from_secret: password2
    LOGURU_LEVEL: WARNING
