---
name: pytest

"on":
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Running pytest
        run: |
          python -m pip install --quiet --no-cache-dir --upgrade uv
          uv run pytest -m 'not network' -vs
